Three patches for time series generation
1. Added "case" argument to env_workflow.get_job_specs()
2. explicitly ignored last two arguments returned from
   env_mach_specific.get_mpirun() -- shouldn't be necessary, but I was seeing
   "ValueError: too many values to unpack" and the error went away with the
   additional _s
3. Remove indexing from options.debug in tseries_generator, since
   parser.add_argument() explicitly casts it as int; avoids
   "TypeError: 'int' object has no attribute '__getitem__'"